name: release_kit
description: >-
  Flutter release toolkit - automatic version bump + multi-platform packaging
  with a unified config.
version: 0.1.1

homepage: https://github.com/jonahzheng/release-kit
repository: https://github.com/jonahzheng/release-kit
environment:
  sdk: '>=3.0.0 <4.0.0'
executables:
  release-kit: release-kit
